Hayden McLemore 

MATH 120 – Final Paper 

The purpose of this project was to explore how water quality measurements vary between monitoring stations across California and whether those measurements show noticeable patterns over time. Instead of determining whether water quality is strictly “good” or “bad,” the focus was on comparing stations relative to one another and identifying general trends. This topic matters because water quality monitoring produces extremely large datasets and being able to summarize and interpret that information is important for understanding environmental conditions at a broader scale. The data used in this project comes from the California Department of Water Resources (DWR) and includes water quality measurements collected from stations throughout the state over several decades. Because the full dataset contains millions of entries, the analysis focuses on a manageable subset while preserving the structure of the original data. I chose three commonly measured parameters to explore: pH, dissolved oxygen, and electrical conductance. These parameters show insight into chemical balance, oxygen availability, and dissolved mineral content in water, and class techniques were used to analyze these attributes of the water to determine quality. 

The analysis began by loading two raw datasets from DWR: a stations dataset containing metadata and a field results dataset containing individual water quality measurements. Since the field results dataset was very large, a representative sample was used to keep the analysis computationally manageable (and possible to put on github). The datasets were merged using a shared station identifier so that each measurement could be analyzed alongside its corresponding station information. Data cleaning involved converting measurement values to numeric form, parsing dates into a datetime format, and filtering the dataset to include only pH, dissolved oxygen, and electrical conductance. Filtering was also used to focus on stations with sufficient data to allow meaningful comparisons. Average values by station were calculated to compare typical conditions across locations. Time-series line plots were created by gathering measurements by year for well-sampled stations, and analysis of the correlation was used to explore relationships between parameters to see if any of them moved together. 

Comparing average values across stations showed clear differences in water quality measurements depending on location. Some stations consistently had higher or lower average values for parameters like pH and dissolved oxygen, suggesting that local conditions influence water quality. These averages provided a useful summary without relying on individual sample readings. Time-series plots showed that yearly averages at stations that were often sampled tended to remain for the most part relatively stable over time. Dissolved oxygen levels showed variation but no major lasting shift, and correlation revealed mostly weak relationships between parameters, with somewhat of positive correlation between electrical conductance and pH, while dissolved oxygen appeared largely independent of the other two. 

Overall, the results suggest that water quality conditions vary across monitoring stations, while many measurements remain relatively consistent over time at specific locations. One strength of this project is its focus on relative comparison rather than a strict classification, which helps avoid overinterpretation of results and better fits the limitations of the dataset. Managing the size of the data and maintaining reproducibility were challenges early on, but these were addressed by organizing raw and cleaned data within the repository. A limitation of the analysis is that only three parameters were examined, and spatial relationships were not explored, also the results should not be interpreted as definitive assessments of water safety, since the analysis is descriptive. With more time, future work could include additional parameters or separate comparisons of groundwater and surface water stations. 

This project used California DWR water quality data to compare measurements across monitoring stations and examine trends over time, and by focusing on relative differences and simple visualizations the analysis demonstrates how large environmental datasets can be cleaned, organized, and interpreted effectively. 
